// ═══════════════════════════════════════
// LaTeXStudio v4.0 — exporter.js
// All export formats: Overleaf ZIP, .tex, HTML, Markdown, plain text,
// workspace JSON, clipboard, PDF (browser print).
// ═══════════════════════════════════════

import {
  sanitizeName, base64ToBinary, checkEnvBalance,
  convertToHTML, convertToMarkdown, convertToText,
  processLatexForOverleaf, validateForExport, buildPrintHTML,
} from './converter.js';
import { state } from './state.js';

/**
 * Robust file download — uses FileSaver if available, falls back to native
 * <a download> anchor. Works without any CDN.
 */
function saveBlob(blob, filename) {
  if (typeof window.saveAs === 'function') {
    try { window.saveAs(blob, filename); return; } catch {}
  }
  // Native fallback
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.style.display = 'none';
  document.body.appendChild(a);
  a.click();
  setTimeout(() => {
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, 100);
}

/** Validate document and return checklist for export modal preview */
export function buildExportChecklist(code, images) {
  const checks = [];
  checks.push({
    severity: code.includes('\\documentclass') ? 'ok' : 'warn',
    message: '\\documentclass declaration',
  });
  checks.push({
    severity: code.includes('\\begin{document}') ? 'ok' : 'warn',
    message: '\\begin{document} present',
  });
  const envBal = checkEnvBalance(code);
  checks.push({
    severity: envBal.balanced ? 'ok' : 'error',
    message: envBal.balanced
      ? 'Environments balanced'
      : 'Environments unbalanced (' + envBal.unmatched.slice(0, 3).join(', ') + ')',
  });
  if (images.length > 0) {
    checks.push({
      severity: 'info',
      message: images.length + ' image' + (images.length === 1 ? '' : 's') + ' will be included',
    });
  }
  checks.push({ severity: 'info', message: '\\graphicspath{{images/}} will be auto-injected' });
  checks.push({ severity: 'info', message: 'Missing packages will be auto-added' });
  return checks;
}

/**
 * Build Overleaf-ready ZIP and trigger download.
 * Reuses processLatexForOverleaf from converter (path rewrite, package injection).
 */
export async function buildOverleafZip(opts) {
  const code = state.get('code');
  const images = state.get('images');
  const projectName = state.get('projectName') || 'latexstudio';
  const safeName = sanitizeName(projectName, 'zip').replace(/\.zip$/, '');

  if (!window.JSZip) {
    throw new Error('JSZip not loaded - cannot create ZIP. Check your internet connection.');
  }

  const zip = new window.JSZip();

  // Process LaTeX (path rewrite + graphicspath inject + auto packages)
  const processed = processLatexForOverleaf(code, images, opts || {
    injectGraphicsPath: true, autoPackages: true,
  });
  zip.file('main.tex', processed);

  // Add images to images/ folder
  if (images.length > 0) {
    const imgFolder = zip.folder('images');
    for (const img of images) {
      const cleanName = sanitizeName(img.name, img.ext);
      try {
        const binary = base64ToBinary(img.data);
        imgFolder.file(cleanName, binary, { binary: true });
      } catch (e) {
        console.warn('Failed to add image', img.name, e);
      }
    }
  }

  // .latexmkrc
  if (opts === undefined || opts.includeReadme !== false) {
    zip.file('.latexmkrc',
      `# .latexmkrc - LaTeXStudio export
$pdf_mode = 1;
$pdflatex = 'pdflatex -interaction=nonstopmode -synctex=1 %O %S';
$bibtex_use = 2;
`);

    zip.file('README.txt',
      `LaTeXStudio Export — Overleaf Upload Instructions
==================================================

PROJECT: ${projectName}
EXPORTED: ${new Date().toISOString()}

How to use this ZIP in Overleaf:

  1. Go to https://www.overleaf.com
  2. New Project -> Upload Project
  3. Drop this ZIP file
  4. Overleaf compiles automatically

Files:
  main.tex      - Your LaTeX source (image paths rewritten to images/)
  images/       - All embedded images
  .latexmkrc    - Build configuration

Tip: If compilation fails, check that all required packages are installed
on Overleaf. Usually all standard packages are available out-of-the-box.

Generated by LaTeXStudio
`);
  }

  // Generate ZIP and download
  const blob = await zip.generateAsync({ type: 'blob' });
  saveBlob(blob, safeName + '.zip');

  return { filename: safeName + '.zip', size: blob.size };
}

/** Export raw LaTeX */
export function exportTex() {
  const code = state.get('code');
  const blob = new Blob([code], { type: 'text/plain' });
  saveBlob(blob, 'main.tex');
}

/** Export rendered HTML */
export function exportHTML() {
  const code = state.get('code');
  const images = state.get('images');
  const projectName = state.get('projectName');
  const html = convertToHTML(code, images, true);
  const blob = new Blob([html], { type: 'text/html' });
  saveBlob(blob, sanitizeName(projectName, 'html'));
}

/** Export Markdown */
export function exportMarkdown() {
  const code = state.get('code');
  const images = state.get('images');
  const projectName = state.get('projectName');
  const md = convertToMarkdown(code, images);
  const blob = new Blob([md], { type: 'text/markdown' });
  saveBlob(blob, sanitizeName(projectName, 'md'));
}

/** Export plain text */
export function exportText() {
  const code = state.get('code');
  const projectName = state.get('projectName');
  const txt = convertToText(code);
  const blob = new Blob([txt], { type: 'text/plain' });
  saveBlob(blob, sanitizeName(projectName, 'txt'));
}

/** Export workspace JSON (code + images + bibliography + snapshots) */
export function exportWorkspace() {
  const data = {
    version: '4.0',
    exportedAt: Date.now(),
    code: state.get('code'),
    images: state.get('images'),
    projectName: state.get('projectName'),
    bibliography: state.get('bibliography'),
    snapshots: state.get('snapshots'),
  };
  const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
  saveBlob(blob, sanitizeName(state.get('projectName'), 'json'));
}

/** Copy LaTeX source to clipboard */
export async function copyToClipboard() {
  try {
    await navigator.clipboard.writeText(state.get('code'));
    return true;
  } catch {
    return false;
  }
}

/** Open print-ready window for "Save as PDF" */
export function exportPDF() {
  const code = state.get('code');
  const images = state.get('images');
  const projectName = state.get('projectName');
  const inner = convertToHTML(code, images, false);
  const printable = buildPrintHTML(inner, projectName);
  const w = window.open('', '_blank', 'width=900,height=1100');
  if (!w) return false;
  w.document.open();
  w.document.write(printable);
  w.document.close();
  return true;
}

/** Top-level dispatch by format id */
export async function runExport(formatId, opts) {
  switch (formatId) {
    case 'zip':       return buildOverleafZip(opts);
    case 'pdf':       return exportPDF();
    case 'tex':       return exportTex();
    case 'html':      return exportHTML();
    case 'md':        return exportMarkdown();
    case 'txt':       return exportText();
    case 'workspace': return exportWorkspace();
    case 'clip':      return copyToClipboard();
    default: throw new Error('Unknown format: ' + formatId);
  }
}
